### ISSUE TITLE
secure the site with https

### ISSUE THREAD

**Issue by groovecoder** [mozilla/www.ccadb.org#12]
It seems important to secure this site with HTTPS. @flamingspaz did this for community & participation static sites using Terraform, Cloudfront, & Lambda:

https://discourse.mozilla.org/t/securing-github-pages-with-terraform-cloudfront-and-lambda/24215

**Comment by wthayer** [comment]
Thanks, I'll work on this.

**Comment by wthayer** [comment]
Just found out that this is being handled in bug 1409786.

**Comment by WilsonKathleen** [comment]
Fixed
