### ISSUE TITLE
Mass Import documentation

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/www.ccadb.org#14]
Please create a separate page for documentation about mass importing intermediate certs. The info is currently here:
https://wiki.mozilla.org/CA:SalesforceCommunity:MassImport

In http://ccadb.org/cas/intermediates please add the following sub-section in the "Adding Intermediate Certificate Data" section, but under the "Clone" sub-section.
~~
Mass Import
CAs who have a large number of intermediate certificates to add to the CCADB may request that their data be mass imported from a spreadsheet or CSV file, by sending email to their root store operator. Doing the mass import process involves a significant amount of manual work, so if you have less than 20 intermediate certificates please enter them by hand. 
~~
Have 'mass import process' link to the new page.

Thanks!

**Comment by wthayer** [comment]
Change has been made - please review.
