### ISSUE TITLE
Improve Incident Reporting Template

### ISSUE THREAD

**Issue by ryancdickson** [mozilla/www.ccadb.org#162]
Placeholder to record and collaborate on future enhancements to the incident reporting template...

1. Specify it's considered "good practice" to respond to incidents in Markdown, rather than attaching a PDF in response to the incident report table defined on CCADB.org
2. Consider including bulleted lists in the template to more directly address areas of interest (i.e., add considerations for whether issuance was stopped and the number of affected certificates) 

... more to come.

**Comment by BenWilson-Mozilla** [comment]
@ryancdickson Does this issue need to be updated and/or reference places in https://github.com/mozilla/www.ccadb.org/pull/186 where these issues are addressed?

**Comment by ryancdickson** [comment]
#186 intends to address these considerations, and more.

Happy to close this issue given our existing trajectory.
