### ISSUE TITLE
Add instructions for updating CAA Domains and Problem Reporting Mechanism as part of anual update (creation of Audit Case)

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/www.ccadb.org#2]
Please add instructions to http://ccadb.org/cas/updates about the "Recognized CAA Domains" and "Problem Reporting Mechanism" fields.

In #3 add bullet:
The 'Recognized CAA Domains' and 'Problem Reporting Mechanism' fields will be automatically filled in when you click on the 'Submit' button, so leave them blank to begin with. You can change them later if needed.

Then add another step (15?) for updating these two fields...
Check that the information in the 'Recognized CAA Domains' and 'Problem Reporting Mechanism' fields is current and of the correct format.
-- 'Recognized CAA Domains' should be a comma-separated list of Certification Authority Authorization (CAA) domain names recognized in a CAA record's issue and issue wild property tags. <include link to further info>
--  'Problem Reporting Mechanism' should provide brief instructions for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter relating to certificates.
<would be good to indicate the preferred format of this data>

**Comment by gerv** [comment]
@WilsonKathleen: I went with:

15. Check that the information in the 'Recognized CAA Domains' and 'Problem
    Reporting Mechanism' fields is current and of the correct format.
    * 'Recognized CAA Domains' should be a comma-separated list of domain names
      recognized in a CAA record's 'issue' and 'issuewild' property tags as
      permitting issuance under this root certificate.
    * 'Problem Reporting Mechanism' should provide brief instructions for
      reporting suspected misissuance, private key compromise, information
      inaccuracy or other types of problem relating to certificates issued
      under this root certificate.

Let me know if that wording is a problem at all. I wanted to avoid "misuse" given the lack of definition of that word.
