### ISSUE TITLE
Add Workflow Summary to https://ccadb.org/cas/updates

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/www.ccadb.org#23]
Some CAs are still getting confused with Audit Cases, and I think it would help to add a very high level list of what they need to do...

Please add the following section to the top of the page in https://ccadb.org/cas/updates
~~
Audit Case Workflow
To provide annual audit statements, the CA does the following:
1. Create an Audit Case in the CCADB - one Audit Case per set of audit statements.
2. Fill in the Auditor, Audit Information, and CP/CPS Information sections.
3. Click on the ‘Add/Update Root Cases’ button to indicate which root certificates are covered in the audit statements, and which audit statements apply to each of those roots.
4. Click on the ‘Edit Test Websites’ button to make sure the test websites are correct.
5. Click on the ‘Audit Letter Validation (ALV)’ button, and work with your auditor to resolve all problems.

After ALV is run, the Audit Case gets automatically assigned to a Root Store Operator for review and final processing. 
~~

**Comment by wthayer** [comment]
fixed in https://github.com/mozilla/www.ccadb.org/commit/42358e320f60be4b7b8406fce326d77a03e24ed2

**Comment by WilsonKathleen** [comment]
Thanks!
