### ISSUE TITLE
Add sentence to top of Instructions section in http://ccadb.org/cas/updates

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/www.ccadb.org#7]
Please add the following sentence to the top of http://ccadb.org/cas/updates#instructions

The following instructions explain how to create an Audit Case in which you will indicate a set of audits and CP/CPS documents, and then you will create corresponding Audit Root Cases to indicate which root certificates were in scope of those audits. 

(There is still frequently confusion causing CAs to create multiple Audit Cases for one set of audits, or to not add the Audit Root Cases.)

**Comment by gerv** [comment]
@WilsonKathleen I have rejigged paragraph 3, which already said this, to embolden the process, and make it more clear that you need one Audit Case per set of Audits, and then one Root Case per root. Please let me know if that will suffice.

**Comment by WilsonKathleen** [comment]
Looks good. Thanks!
