### ISSUE TITLE
Replace "CA" with "CA Owner" in CCADB Policy

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [mozilla/www.ccadb.org#90]
The CCADB is using "CA Owner" instead of "CA" in many documents. This should be done in the CCADB Policy, too.

**Comment by ChristopherRC** [comment]
I think we achieved this with the recent CCADB policy update and the general cleanup branches.

**Comment by khadar1020** [comment]
yeah, we have achieved this in new policy update.
